dam_name: rear_left_dam


data_input_methods:
	pins:
		// maybe switch english name and part number?
		PA0:
			sensor: "32313757"
		PA1:
			sensor: "32313757"
		PA3:
			sensor: "185624"
	
	can_sensors:
		can_sensor_1: "MM5.10-R"
		can_sensor_2: "IRTS-V2"
	
parameters_produced:
	oil_cooler_pressure_in:
		gophercan_id: xx
		produced_by: PA0
			
			
		
	oil_cooler_pressure_out:
		gophercan_id: xx
		produced_by: PA1
			depends_on: pressure
		
	lateral_acceleration:
		gophercan_id: xx
		produced_by: can_sensor_1
			depends_on: x_acceleration
		
	longitudinal_acceleration:
		gophercan_id: xx
		produced_by: can_sensor_1
		
	yaw_rate:
		gophercan_id: xx
		produced_by: can_sensor_1
		
	back_left_tire_temp:
		gophercan_id: xx
		produced_by: can_sensor_2
			depends_on:
				
		


buckets:
	bucket_1:
		id: 1
		frequency: 10
		parameters:
			oil_cooler_pressure_in:
			oil_cooler_pressure_out:
	bucket_2:
		id: 2
		frequency: 50
			lateral_acceleration:
			longitudinal_acceleration:
	
	bucket_3:
		id: 3
		frequency: 1
			back_left_tire_temp: