dam_name: rear_left_dam
gophercan_module_id: 2

data_input_methods:
	pins:
		// maybe switch english name and part number?
		PA0:
			sensor: "32313757"
			min_frequency: 10
					
		PA1:
			sensor: "32313757"
			min_frequency: 20
			
		PA3:
			sensor: "185624"
			min_frequency: 30
			
	
	can_sensors:
		can_sensor_1: "MM5.10-R"
		can_sensor_2: "IRTS-V2"
			
parameters_produced:
	oil_cooler_pressure_in:
		gophercan_id: xx
		produced_by: PA0
			depends_on: pressure
		filter_subparams:
			oil_cooler_pressure_in_lowpass_1000:
				gophercan_id: xx
				filter_type: low_pass
				filter_value: 1000
		buffering:
			num_samples_buffered: 100

			
	oil_cooler_pressure_out:
		gophercan_id: xx
		produced_by: PA1
			depends_on: pressure
		filter_subparams:
			oil_cooler_pressure_in_lowpass_1000:
				filter_type: low_pass
				filter_value: 1000
				gophercan_id: xx
		buffering:
			num_samples_buffered: 100
			
	lateral_acceleration:
		gophercan_id: 2
		produced_by: can_sensor_1
			depends_on: x_acceleration
		filter_subparams:
		buffering:
				num_samples_buffered: 100
			
	longitudinal_acceleration:
		gophercan_id: xx
		produced_by: can_sensor_1
			depends_on: y_acceleration
		filter_subparams:
		buffering:
				num_samples_buffered: 100
			
		
	yaw_rate:
		gophercan_id: xx
		produced_by: can_sensor_1
			depends_on: yaw_rate
		filter_subparams:
		buffering:
				num_samples_buffered: 100
			
		
	back_left_tire_temp:
		gophercan_id: xx
		produced_by: can_sensor_2
			depends_on: 
				channel_1_temp
				channel_2_temp
				channel_3_temp
				channel_4_temp
				channel_5_temp
				channel_6_temp
				channel_7_temp
				channel_8_temp
				channel_9_temp
				channel_10_temp
				channel_11_temp
				channel_12_temp
				channel_13_temp
				channel_14_temp
				channel_15_temp
				channel_16_temp
			dependency_association: average		
		filter_subparams:
		buffering:
				num_samples_buffered: 100
					
		


buckets:
	bucket_1:
		id: 1
		frequency: 10
		parameters:
			oil_cooler_pressure_in:
			oil_cooler_pressure_out:
	bucket_2:
		id: 2
		frequency: 50
			lateral_acceleration:
			longitudinal_acceleration:
	
	bucket_3:
		id: 3
		frequency: 1
			back_left_tire_temp: